export const admin_access = [
  {
    function_name: 'Admin Management',
    full_access: true,
    create: true,
    read: true,
    update: true,
    remove: true,
  },
  {
    function_name: 'Registration/Room management',
    full_access: true,
    create: true,
    read: true,
    update: true,
    remove: true,
  },
  {
    function_name: 'Announcement',
    full_access: true,
    create: true,
    read: true,
    update: true,
    remove: true,
  },
  {
    function_name: 'Facilities Reservation',
    full_access: true,
    create: true,
    read: true,
    update: true,
    remove: true,
  },
  {
    function_name: 'Nearby',
    full_access: true,
    create: true,
    read: true,
    update: true,
    remove: true,
  },
  {
    function_name: 'Chat',
    full_access: false,
    create: true,
    read: true,
    update: false,
    remove: false,
  },
  {
    function_name: 'Service Center',
    full_access: true,
    create: true,
    read: true,
    update: true,
    remove: true,
  },
  {
    function_name: 'Payment',
    full_access: true,
    create: true,
    read: true,
    update: true,
    remove: true,
  },
  {
    function_name: 'Smart Locker',
    full_access: true,
    create: true,
    read: true,
    update: true,
    remove: true,
  },
];

export const juristic_access = [
  {
    function_name: 'Admin Management',
    full_access: false,
    create: false,
    read: false,
    update: false,
    remove: false,
  },
  {
    function_name: 'Registration/Room management',
    full_access: true,
    create: true,
    read: true,
    update: true,
    remove: true,
  },
  {
    function_name: 'Announcement',
    full_access: true,
    create: true,
    read: true,
    update: true,
    remove: true,
  },
  {
    function_name: 'Facilities Reservation',
    full_access: true,
    create: true,
    read: true,
    update: true,
    remove: true,
  },
  {
    function_name: 'Nearby',
    full_access: true,
    create: true,
    read: true,
    update: true,
    remove: true,
  },
  {
    function_name: 'Chat',
    full_access: false,
    create: true,
    read: true,
    update: false,
    remove: false,
  },
  {
    function_name: 'Service Center',
    full_access: false,
    create: false,
    read: true,
    update: true,
    remove: false,
  },
  {
    function_name: 'Payment',
    full_access: false,
    create: true,
    read: true,
    update: true,
    remove: false,
  },
  {
    function_name: 'Smart Locker',
    full_access: true,
    create: true,
    read: true,
    update: true,
    remove: true,
  },
];
