const locationList = [
    { name: "Bangkok", status: false, value: "Bangkok",lat:13.736717,long:100.523186},
    { name: "Samut Prakan", status: false, value: "Samut Prakan",lat:13.59934,long:100.59675},
    { name: "Nonthaburi", status: false, value: "Nonthaburi"},
    { name: "Pathum Thani", status: false, value: "Pathum Thani"},
    { name: "Phra Nakhon Si Ayutthaya", status: false, value: "Phra Nakhon Si Ayutthaya"},
    { name: "Ang Thong", status: false, value: "Ang Thong"},
    { name: "Loburi", status: false, value: "Loburi"},
    { name: "Sing Buri", status: false, value: "Sing Buri"},
    { name: "Chai Nat", status: false, value: "Chai Nat"},
    { name: "Saraburi", status: false, value: "Saraburi"},
    { name: "Chon Buri", status: false, value: "Chon Buri"},
    { name: "Rayong", status: false, value: "Rayong"},
    { name: "Chanthaburi", status: false, value: "Chanthaburi"},
    { name: "Trat", status: false, value: "Trat"},
    { name: "Chachoengsao", status: false, value: "Chachoengsao"},
    {name: "Prachin Buri", status: false, value: "Prachin Buri"},
    { name: "Nakhon Nayok", status: false, value: "Nakhon Nayok"},
    { name: "Sa Kaeo", status: false, value: "Sa Kaeo"},
    { name: "Nakhon Ratchasima", status: false, value: "Nakhon Ratchasima"},
    { name: "Buri Ram", status: false, value: "Buri Ram"},
    { name: "Surin", status: false, value: "Surin"},
    { name: "Si Sa Ket", status: false, value: "Si Sa Ket"},
    { name: "Ubon Ratchathani", status: false, value: "Ubon Ratchathani"},
    { name: "Yasothon", status: false, value: "Yasothon"},
    { name: "Chaiyaphum", status: false, value: "Chaiyaphum"},
    { name: "Amnat Charoen", status: false, value: "Amnat Charoen"},
    { name: "Nong Bua Lam Phu", status: false, value: "Nong Bua Lam Phu"},
    { name: "Khon Kaen", status: false, value: "Khon Kaen"},
    { name: "Udon Thani", status: false, value: "Udon Thani"},
    { name: "Loei", status: false, value: "Loei"},
    { name: "Nong Khai", status: false, value: "Nong Khai"},
    { name: "Maha Sarakham", status: false, value: "Maha Sarakham"},
    { name: "Roi Et", status: false, value: "Roi Et"},
    { name: "Kalasin", status: false, value: "Kalasin"},
    { name: "Sakon Nakhon", status: false, value: "Sakon Nakhon"},
    { name: "Nakhon Phanom", status: false, value: "Nakhon Phanom"},
    { name: "Mukdahan", status: false, value: "Mukdahan"},
    { name: "Chiang Mai", status: false, value: "Chiang Mai"},
    { name: "Lamphun", status: false, value: "Lamphun"},
    { name: "Lampang", status: false, value: "Lampang"},
    { name: "Uttaradit", status: false, value: "Uttaradit"},
    { name: "Phrae", status: false, value: "Phrae"},
    { name: "Nan", status: false, value: "Nan"},
    { name: "Phayao", status: false, value: "Phayao"},
    { name: "Chiang Rai", status: false, value: "Chiang Rai"},
    { name: "Mae Hong Son", status: false, value: "Mae Hong Son"},
    { name: "Nakhon Sawan", status: false, value: "Nakhon Sawan"},
    { name: "Uthai Thani", status: false, value: "Uthai Thani"},
    { name: "Kamphaeng Phet", status: false, value: "Kamphaeng Phet"},
    { name: "Tak", status: false, value: "Tak"},
    { name: "Sukhothai", status: false, value: "Sukhothai"},
    { name: "Phitsanulok", status: false, value: "Phitsanulok"},
    { name: "Phichit", status: false, value: "Phichit"},
    { name: "Phetchabun", status: false, value: "Phetchabun"},
    { name: "Ratchaburi", status: false, value: "Ratchaburi"},
    { name: "Kanchanaburi", status: false, value: "Kanchanaburi"},
    { name: "Suphan Buri", status: false, value: "Suphan Buri"},
    { name: "Nakhon Pathom", status: false, value: "Nakhon Pathom"},
    { name: "Samut Sakhon", status: false, value: "Samut Sakhon"},
    { name: "Samut Songkhram", status: false, value: "Samut Songkhram"},
    { name: "Phetchaburi", status: false, value: "Phetchaburi"},
    { name: "Prachuap Khiri Khan", status: false, value: "Prachuap Khiri Khan"},
    { name: "Nakhon Si Thammarat", status: false, value: "Nakhon Si Thammarat"},
    { name: "Krabi", status: false, value: "Krabi"},
    { name: "Phangnga", status: false, value: "Phangnga"},
    { name: "Phuket", status: false, value: "Phuket"},
    { name: "Surat Thani", status: false, value: "Surat Thani"},
    { name: "Ranong", status: false, value: "Ranong"},
    { name: "Chumphon", status: false, value: "Chumphon"},
    { name: "Songkhla", status: false, value: "Songkhla"},
    { name: "Satun", status: false, value: "Satun"},
    { name: "Trang", status: false, value: "Trang"},
    { name: "Phatthalung", status: false, value: "Phatthalung"},
    { name: "Pattani", status: false, value: "Pattani"},
    { name: "Yala", status: false, value: "Yala"},
    { name: "Narathiwat", status: false, value: "Narathiwat"},
    { name: "buogkan", status: false, value: "buogkan"}
];
export{locationList}